### ISSUE TITLE
Error de dedo

### ISSUE THREAD

**Issue by emmaboes** [Socialtic/mx-elections-2021#1]
En el archivo 01-structure.md me parece que hay un error de dedo en el texto: 

 _And for any instance or entity on the endpoints the get, put and delete methods **area** available._
 
 ¿Sólo debería decir **are**?

**Comment by penserbjorne** [comment]
Hola! Es correcto.

Ya lo corregí.

Dejare abierto el issue por si hay más errores comentarlos aquí.

Gracias @emmaboes !
