### ISSUE TITLE
Crear vista de Swagger

### ISSUE THREAD

**Issue by xuxoramos** [Socialtic/mx-elections-2021#3]
Para agregar autenticación y monitoreo al API con [API Gateway de AWS](https://aws.amazon.com/api-gateway/) hay que hacer que la app tenga una ruta `/swagger`.

Podemos incorporar [flasgger](https://github.com/flasgger/flasgger) para generar en automático este front y permitir que lo consuma API Gateway.

**Comment by penserbjorne** [comment]
Hola!

Muy bien, trabajare en añadir flasgger.

**Comment by xuxoramos** [comment]
Seguí este tutorial que incorpora Flask, SqlAlchemy y Swagger para que chequemos API Gateway:
1. Flask + SqlAlchemy: https://gerrysabar.medium.com/install-sqlalchemy-to-flask-1-0-2-python-3-247705e742c0
2. Flask + Swagger: https://gerrysabar.medium.com/basic-api-crud-with-flask-1-0-3-swagger-8509de52fbbc
3. Flask + SqlAlchemy + Swagger: https://gerrysabar.medium.com/basic-crud-with-flask-1-0-2-swagger-sqlalchemy-d26ae303e99d

El Jueves te muestro el resultado de API Gateway.

**Comment by xuxoramos** [comment]
> Hola!
> 
> Muy bien, trabajare en añadir flasgger.

Yo no pude hacer jalar el flasgger, y usé los tutoriales que te pongo arriba.

**Comment by penserbjorne** [comment]
Hola!

Al parecer el proyecto de [Flask-RESTPlus esta muerto](https://github.com/noirbizarre/flask-restplus/issues/770), esta era la herramienta que se utilizaba en los tutoriales.

Probare con [Flask-RESTX](https://github.com/python-restx/flask-restx) el cual es un fork de RESTPlus.

**Comment by xuxoramos** [comment]
> Hola!
> 
> Al parecer el proyecto de [Flask-RESTPlus esta muerto](https://github.com/noirbizarre/flask-restplus/issues/770), esta era la herramienta que se utilizaba en los tutoriales.
> 
> Probare con [Flask-RESTX](https://github.com/python-restx/flask-restx) el cual es un fork de RESTPlus.

Ya chequé el proyecto RESTX y se me hace que es un muy buen reemplazo del RESTPlus. Vientos!

**Comment by penserbjorne** [comment]
¡Listo!

[El código ha sido swaggerizado](https://github.com/Socialtic/mx-elections-2021/pull/6).
